# Generated by Django 5.2.1 on 2025-11-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paypal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=150)),
                ("status", models.BooleanField(default=0)),
                ("sandbox", models.BooleanField(default=1)),
                (
                    "transaction",
                    models.CharField(
                        choices=[("Auth", "Authorization"), ("Sale", "Sale")],
                        max_length=4,
                    ),
                ),
                ("sort_order", models.IntegerField(default=10)),
            ],
        ),
    ]
