# Generated by Django 5.2.1 on 2025-11-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="", max_length=10)),
                ("title", models.CharField(default="Payment Title", max_length=20)),
                ("status", models.BooleanField(default=0)),
            ],
        ),
    ]
