# Generated by Django 5.2.1 on 2025-11-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=8)),
                (
                    "type",
                    models.CharField(
                        choices=[("A", "Absolute Value"), ("P", "Percentage")],
                        default="P",
                        max_length=20,
                    ),
                ),
                ("status", models.BooleanField(default=1)),
                ("sort_order", models.IntegerField(default=1)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                "verbose_name": "Tax",
                "verbose_name_plural": "Taxes",
            },
        ),
    ]
