"""
Django settings for appoint project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import environ
import json

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, True)
)
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY",default="django-insecure-jd$y&!87ppw8l#nrz+*12x93t4n*s5+g9f1^^#m!q+rce(&f*f")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =env("DEBUG")





ALLOWED_HOSTS = [
    h.strip()
    for h in env("ALLOWED_HOSTS", default="").split(",")
    if h.strip()
]

MEDIA_URL = "/schedule/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

MEDIA_ICACHE = os.path.join(BASE_DIR, "media/cache/")
MEDIA_STATIC = os.path.join(BASE_DIR, "media/")
ICACHE_URL = MEDIA_IURL = "/schedule/media/cache/"
# Application definition

INSTALLED_APPS = [
    #'django.forms',
    #'custadmin',
    "jazzmin",
    "config",
    #'information',
    "taxes",
    "payment",
   
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "category",
    "doctor",
    "fm",
    'book',
    'customer',
   'banners',
    'cart',
    'orders',
    'information'
    #'cart'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "appoint.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "appoint.wsgi.application"

EMAIL_ADMIN=env('EMAIL_ADMIN')
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
if env('DEVELOPMENT_MODE'):
 CURRENCY_SETTINGS =  {
    "locale": env("CURRENCY_LOCALE"),
    "currency_code": env("CURRENCY_CODE"),
    "locjs": env("CURRENCY_LOCJS"),
}
 EMAIL_ADMIN=env('EMAIL_ADMIN')
 db_conn = env("DB_CONNECTION")
 db_db=env("DB_DATABASE")
 db_username=env("DB_USERNAME")
 db_password=env("DB_PASSWORD")
 db_host=env("DB_HOST")
 db_port=env("DB_PORT")
 SITE_URL=env('SITE_URL')
 SITE_ADMIN_URL=env('SITE_ADMIN_URL')
else:
    EMAIL_ADMIN=os.getenv('EMAIL_ADMIN')
    CURRENCY_SETTINGS =  {
    "locale": os.getenv("CURRENCY_LOCALE"),
    "currency_code": os.getenv("CURRENCY_CODE"),
    "locjs": os.getenv("CURRENCY_LOCJS"),
}
    db_conn = os.getenv("DB_CONNECTION")
    db_db=os.getenv("DB_DATABASE")
    db_username=os.getenv("DB_USERNAME")
    db_password=os.getenv("DB_PASSWORD")
    db_host=os.getenv("DB_HOST")
    db_port=os.getenv("DB_PORT")
    SITE_URL=os.getenv('SITE_URL')
    SITE_ADMIN_URL=os.getenv('SITE_ADMIN_URL')
DATABASES = {
    "default": {
        #'ENGINE': if db_conn then 'django.db.backends.postgresql',
        #'NAME': 'postgres',
        "ENGINE": db_conn,
        "NAME": db_db,
        "USER":db_username,
        "PASSWORD": db_password,
        "HOST": db_host,
        "PORT":db_port,
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    },
    "default2": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True
LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale/"),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')
STATIC_ROOT2 = os.path.join(BASE_DIR, 'static')
# Folder(s) where Django will look for your app-level static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/assets/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
