# Generated by Django 5.2.1 on 2025-11-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("seo_url", models.CharField(max_length=250, unique=True)),
                ("content", models.TextField(blank=True)),
                ("status", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=10)),
            ],
        ),
    ]
