# Generated by Django 5.2.1 on 2025-12-09 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dated", models.DateField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("slot", models.CharField(max_length=20)),
                ("device_id", models.CharField(blank=True, max_length=50)),
                ("user_id", models.IntegerField(blank=True, default=0)),
                (
                    "doctor_id",
                    models.ForeignKey(
                        db_column="doctor_id",
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.doctor",
                    ),
                ),
            ],
        ),
    ]
