# Generated by Django 5.2.1 on 2025-11-04 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("category", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dated", models.DateField(max_length=20)),
                ("slot", models.CharField(max_length=20)),
                ("desc", models.TextField(blank=True)),
                ("name", models.CharField(max_length=60)),
                ("phone", models.CharField(max_length=15)),
                ("order_id", models.IntegerField(blank=True, default=0)),
                (
                    "email",
                    models.CharField(
                        blank=True, default="demo@gmail.com", max_length=150
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UN", "UNAVAILABLE"),
                            ("AV", "AVAILABLE"),
                            ("CAN", "CANCELLED"),
                            ("BOOKED", "BOOKED"),
                            ("REFUNDED", "REFUNDED"),
                        ],
                        default="AV",
                        max_length=15,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=150)),
                ("user_id", models.IntegerField(blank=True, default=0)),
                ("order_item_id", models.IntegerField(blank=True, default=0)),
                ("extra_info", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="BookHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dated",
                    models.DateField(default=django.utils.timezone.now, max_length=20),
                ),
                ("status", models.CharField(max_length=20)),
                ("info", models.TextField(blank=True)),
                (
                    "book_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctor.book"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("sunday", models.TextField(default="00:00-00:00#0")),
                ("monday", models.TextField(default="10:00-18:00#500")),
                ("tuesday", models.TextField(default="10:00-18:00#500")),
                ("wednesday", models.TextField(default="10:00-18:00#500")),
                ("thursday", models.TextField(default="10:00-18:00#500")),
                ("friday", models.TextField(default="10:00-18:00#500")),
                ("saturday", models.TextField(default="00:00-00:00#0")),
                (
                    "slot",
                    models.IntegerField(default=1800, help_text="Session in seconds"),
                ),
                ("off", models.TextField(blank=True)),
                (
                    "license_number",
                    models.CharField(default="abcde83939", max_length=50),
                ),
                ("specialization", models.CharField(blank=True, max_length=100)),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("qualification", models.TextField(blank=True)),
                ("image", models.CharField(blank=True, default="", max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="doctor_id",
            field=models.ForeignKey(
                db_column="doctor_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.doctor",
            ),
        ),
        migrations.CreateModel(
            name="DoctorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "expertise_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("years_in_category", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor_Category",
                "verbose_name_plural": "Doctor_Categories",
            },
        ),
        migrations.AddField(
            model_name="doctor",
            name="categories",
            field=models.ManyToManyField(
                related_name="doctors",
                through="doctor.DoctorCategory",
                to="category.category",
            ),
        ),
        migrations.CreateModel(
            name="DoctorCategoryRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Rating from 1 to 5 stars",
                    ),
                ),
                ("review", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.doctorcategory",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Category Rating",
                "verbose_name_plural": "Doctor Category Ratings",
            },
        ),
        migrations.CreateModel(
            name="DoctorSpecial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sdate", models.DateField()),
                ("hours", models.TextField(default="08:00-12:00")),
                ("off", models.TextField(blank=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor",
                        to="doctor.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Special Day Timings",
                "verbose_name_plural": "Doctor Special Days",
            },
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "BOOKED")),
                fields=("dated", "doctor_id", "slot"),
                name="unique2_booking",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="doctorcategory",
            unique_together={("doctor", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="doctorcategoryrating",
            unique_together={("doctor_category", "patient")},
        ),
    ]
