# Generated by Django 5.2.1 on 2026-01-12 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0002_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="book_id",
            new_name="book",
        ),
    ]
