# Generated by Django 5.2.1 on 2025-11-04 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("category", "0001_initial"),
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("device_id", models.CharField(blank=True, max_length=120)),
                ("payment_method", models.CharField(max_length=20)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("total", models.DecimalField(decimal_places=2, max_digits=7)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.CharField(blank=True, max_length=200)),
                ("currency_code", models.CharField(blank=True, max_length=4)),
                ("user_id", models.IntegerField(blank=True, default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CREATED", "Created"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dated",
                    models.DateField(default=django.utils.timezone.now, max_length=20),
                ),
                ("status", models.CharField(max_length=20)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=50)),
                ("dated", models.DateField()),
                ("category", models.CharField(max_length=10)),
                ("doctor", models.CharField(max_length=50)),
                ("slot", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "category_id",
                    models.ForeignKey(
                        db_column="category_id",
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="category.category",
                    ),
                ),
                (
                    "doctor_id",
                    models.ForeignKey(
                        db_column="doctor_id",
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="doctor.doctor",
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        db_column="order_id",
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderTotals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("total", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
        ),
    ]
